application: happy-birthday-481
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: https://iamnotfound8.github.io/website/iamnotfound8/website/css
  static_dir: css

- url: https://iamnotfound8.github.io/website/iamnotfound8/website/javascript
  static_dir: javascript
  
- url: https://iamnotfound8.github.io/website/iamnotfound8/website/images
  static_dir: images

- url: https://iamnotfound8.github.io/website/iamnotfound8/website/.*
  script: main.app
  
libraries:
- name: webapp2
  version: "2.5.2"
